linters-settings:
  exhaustive:
    default-signifies-exhaustive: false
  goimports:
    local-prefixes: github.com/kubernetes-sigs/external-dns
  golint:
    min-confidence: 0.9
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dogsled
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - deadcode
        - depguard
        - dogsled
        - gofmt
        - goimports
        - golint
        - goprintffuncname
        - gosimple
        - govet
        - ineffassign
        - interfacer
        - misspell
        - nolintlint
        - rowserrcheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unused
        - varcheck
        - whitespace


#run:
#  skip-dirs:
#    - test/testdata_etc
#    - internal/cache
#    - internal/renameio
#    - internal/robustio

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
#service:
#  golangci-lint-version: 1.23.x # use the fixed version to not introduce new linters unexpectedly
#  prepare:
#    - echo "here I can run custom commands, but no preparation needed for this repo"
