dist: trusty

os:
- linux

git:
  submodules: false

language: go

go:
- 1.7
- 1.8
- tip

before_install:
- go get github.com/mattn/goveralls
- go get -u github.com/alecthomas/gometalinter
- sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive

install:
- gometalinter --install

script:
- hack/verify-all.sh -v
- goveralls -service=travis-ci
