on: [push]

jobs:
  build_and_deploy_docker:
    runs-on: ubuntu-latest
    name: This job will build and deploy to docker hub
    steps:
    - uses: actions/checkout@v1
    - name: Build Action 
      env: # Or as an environment variable
          docker_login: ${{ secrets.docker_login }}
          docker_token: ${{ secrets.docker_token }}      
      run: |
        bash ./init.sh
