on: [push]

jobs:
  build_and_deploy_docker:
    runs-on: ubuntu-latest
    name: This job will build and deploy to docker hub
    steps:
    - uses: actions/checkout@v1
    - name: Build Action 
      run: |
        pwd
        ls -lR  /home/runner/work
