name: "Pull Request Labeler"
on:
- pull_request

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        if: contains(github.repository, 'kubernetes-sigs/external-dns')
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
